apiVersion: apps/v1
kind: Deployment
metadata:
  name: adahandle-resolver
spec:
  replicas: {{ .Values.adaHandleResolver.replicas }}
  selector:
    matchLabels:
      app: adahandle-resolver
  template:
    metadata:
      labels:
        app: adahandle-resolver
    spec:
      containers:
      - name: adahandle-resolver
        env:
          - name: SPRING_ACTIVE_PROFILES
            value: {{ .Values.adaHandleResolver.spring.activeProfiles }}
          - name: PORT
            value: {{ .Values.adaHandleResolver.port }}
          - name: DB_URL
            value: {{ .Values.adaHandleResolver.database.url }}
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.adaHandleResolver.database.secret.name }}
                key: {{ .Values.adaHandleResolver.database.secret.userKey }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.adaHandleResolver.database.secret.name }}
                key: {{ .Values.adaHandleResolver.database.secret.passwordKey }}
        image: {{ .Values.adaHandleResolver.image.repository }}:{{ .Values.adaHandleResolver.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
          - name: api
            containerPort: {{ .Values.adaHandleResolver.port }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
  {{- if .Values.adaHandleResolver.database.persistence.enabled }}
        volumeMounts:
          - name: data-volume
            mountPath: /data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: adahandle-resolver-pvc
  {{- end }}
    revisionHistoryLimit: 2