{{ with .Values.adaHandleResolver.database.persistence }}
  {{ if .enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adahandle-resolver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .storage.size }}
  {{- end }}
{{ end }}