server:
  port: ${PORT:9095}

spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:mainnet,h2}
  main:
    banner-mode: off
  flyway:
    locations:
      - classpath:db/migration/{vendor}
      - classpath:db/migration/adahandle
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:h2:./data/db}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}

apiPrefix: /api/v1

logging:
  file:
    name: ./logs/adahandle-resolver.log

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

store:
  cardano:
    host: ${REMOTE_NODE_URL:relays-new.cardano-mainnet.iohk.io}
    port: ${REMOTE_NODE_PORT:3001}
    protocol-magic: 764824073
    # 47931310 is the slot number close to the first AdaHandle minting transaction
    # 89f93419845d5... is the hash that corresponds to the block with the above slot number
    sync-start-slot: 47931310
    sync-start-blockhash: 89f93419845d5f6ce8040fd5eeedda93d764c8569f7c2cc6802a8429a0da877b
  blocks:
    epoch-calculation-interval=14400:  # 14400 = 4 hours
---
spring:
  config:
    activate:
      on-profile: disable-indexer

store:
  sync-auto-start: false
---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/adahandle}
---
spring:
  config:
    activate:
      on-profile: h2
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: preprod
store:
  cardano:
    host: ${REMOTE_NODE_URL:preprod-node.world.dev.cardano.org}
    port: ${REMOTE_NODE_PORT:30000}
    protocol-magic: ${PROTOCOL_MAGIC:1}
    sync-start-slot: 691200
    sync-start-blockhash: f600c12d960d1fe3629573717f9f5d2a62b5420245703d1b9435250a8c885c83
---
spring:
  config:
    activate:
      on-profile: preview
store:
  cardano:
    host: ${REMOTE_NODE_URL:preview-node.world.dev.cardano.org}
    port: ${REMOTE_NODE_PORT:30002}
    protocol-magic: ${PROTOCOL_MAGIC:2}
    sync-start-slot: 1468836
    sync-start-blockhash: 706e7ba53bd141f48c3de44517b67fd8758f46215694891ed486f8d91fb1a51e
---
spring:
  config:
    activate:
      on-profile: local-node
store:
  cardano:
      n2c-node-socket-path: ${LOCAL_NODE_SOCKET_PATH}
      n2c-host: ${LOCAL_NODE_HOST}
      n2c-port: ${LOCAL_NODE_PORT}
---