{{ if eq .Values.database.type "h2" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: h2-secrets
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.database.h2.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.h2.password | default (randAlphaNum 16) | b64enc | quote }}
{{ end }}