{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adahandle-resolver.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "adahandle-resolver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: "adahandle-resolver.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- range $domain := .Values.ingress.additionalDomains }}
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    {{- end }}
  tls:
    - hosts:
        - "adahandle-resolver.{{ .Values.domain }}"
{{ with .Values.ingress.additionalDomains }}
        {{- toYaml . | nindent 8 }}
{{ end }}
{{ end }}
